### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by cuekoo** [pmneila/PyMaxflow#17]
How to solve the following issue?

    clang: error: no such file or directory: 'maxflow/src/_maxflow.c'

    clang: error: no input files

    error: command 'cc' failed with exit status 1

**Comment by pmneila** [comment]
Hi,

I need more details. How are you building the package? Are you using `python setup.py build` or `pip install PyMaxflow`?

What versions are you using for `distutils`, `setuptools` and `cython`? You can get the versions with:
```sh
$ python -c 'import distutils; print distutils.__version__'
$ python -c 'import setuptools; print setuptools.__version__'
$ python -c 'import cython; print cython.__version__'
```

As a first guess, [this thread](https://groups.google.com/forum/#!topic/cython-users/n5UpJmWUzag) might be related to your problem, and they claim that installing the `distribute` package fixes it.

**Comment by cuekoo** [comment]
@pmneila Thank you. The solution works.

For later reference, the details are:
1. Both `python setup.py build` and `pip install PyMaxFlow` didn't work
2. `distutils` version 2.7.5; `setuptools` version 14.3.1; `cython` version 0.22
