### ISSUE TITLE
ImportError: No module named networkx

### ISSUE THREAD

**Issue by mrgloom** [pmneila/PyMaxflow#28]
After `sudo pip install pymaxflow` on Ubuntu 14.04

Using this example:
https://github.com/pmneila/PyMaxflow/blob/master/examples/binary_restoration.py

I get error:
~~~
python binary_restoration.py
Traceback (most recent call last):
  File "binary_restoration.py", line 19, in <module>
    graph = g.get_nx_graph()
  File "maxflow/src/_maxflow.pyx", line 448, in _maxflow.GraphInt.get_nx_graph (maxflow/src/_maxflow.cpp:3390)
ImportError: No module named networkx
~~~

**Comment by mrgloom** [comment]
Problem solved with: `sudo pip install networkx`

**Comment by pmneila** [comment]
Hi,

Yes, networkx is an optional package for PyMaxflow since it is only used in the function get_nx_graph, which is there for debugging purposes. That's why it is not included in the dependencies and not installed when you install PyMaxflow. 

However, you can install it manually as you did if you need to call get_nx_graph. 

Regards.

**Comment by alma-frankenstein** [comment]
Also, anyone using python3 might try installing it with pip3.

**Comment by 0102TH** [comment]
I successfully done this inWindows 10 with carla 0.9.5.
Refer to the figure below.
![image](https://user-images.githubusercontent.com/47203090/69847010-d5478680-12b0-11ea-9f93-135d45925884.png)

![image](https://user-images.githubusercontent.com/47203090/69846920-8994dd00-12b0-11ea-9aa0-0fbdf0af5122.png)

**Comment by apoorvpandey0** [comment]
I'm trying to run this and it has sooo many missing dependencies in Python 2.7 pythonlib,matplotlib,tkinter just to name a few, can anyone please write thee down somewhere.
