### ISSUE TITLE
Python3 fastmin uses xrange istead of range

### ISSUE THREAD

**Issue by MMarus** [pmneila/PyMaxflow#30]
There is no xrange in python3 therefore when using fastmin in python3 it screams about the xrange.

**Comment by pmneila** [comment]
You're absolutely right. I'm fixing that.

**Comment by pmneila** [comment]
It's done. I also uploaded the new version (1.2.8) to PyPI, so you should be able to update it with `pip`. Thank you for letting me know this error.
