### ISSUE TITLE
Upgrade to core 3.04

### ISSUE THREAD

**Issue by Skielex** [pmneila/PyMaxflow#32]
Firstly, thanks a lot for sharing this wrapper for the maxflow library. Really useful!

Kolmogorov released version 3.04, which should solve overflow issues for large graphs.
Any change you'd be upgrading you wrapper to use the new version?

Edit: I noticed Kolmogorov used ```long```, but to ensure 64 bit length on Windows, perhaps ```long long``` should be used.

**Comment by pmneila** [comment]
Done!

Thank you for letting me know. I used `long long` following your suggestion.
