### ISSUE TITLE
this can handle image instance segmentation?

### ISSUE THREAD

**Issue by Jackandrome** [pmneila/PyMaxflow#36]
i wanna use graph cut to segment instances in an image ,is it helpful ?

**Comment by h4k1m0u** [comment]
You can look at the [second example] (http://pmneila.github.io/PyMaxflow/tutorial.html#binary-image-restoration) in the tutorials section as a segmentation problem.

So yes, normally graph cuts work for segmentation problems, plus they take into account the spatial proximity between pixels.

**Comment by scarletteshu** [comment]
hey there,
my issue is:
i have a mask(binary), which indicates possible foreground of the image, and one correspoding original image. how can i use this for segmented region smoothing? (meaning based on the mask to segment the corresponding region of the image)
