### ISSUE TITLE
unable to install on Mac using either pip or manual installation

### ISSUE THREAD

**Issue by karthickgopalswamy** [pmneila/PyMaxflow#40]
However I try to build, it results in the same error as below.
     
"Using deprecated NumPy API, disable it with "          "#define
      NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
#warning "Using deprecated NumPy API, disable it with " \
 ^
maxflow/src/_maxflow.cpp:637:10: fatal error: 'ios' file not found
#include "ios"
         ^~~~~

**Comment by timmh** [comment]
adding `CFLAGS='-stdlib=libc++'` worked for me, e.g.: `CFLAGS='-stdlib=libc++' pip install PyMaxflow` (similar to https://github.com/huggingface/neuralcoref/issues/97)

**Comment by pmneila** [comment]
Binary wheels are available via pip now for multiple platforms including Mac. Hopefully this problem will not recur.

Best
