### ISSUE TITLE
Support for newest networkx

### ISSUE THREAD

**Issue by rajkataria** [pmneila/PyMaxflow#47]
The current version of the library is incompatible with networkx. I believe networkx has changed the way that nodes are accessed. From g.node[n] -> g.nodes[n]

(Pdb) g.get_nx_graph()
*** AttributeError: 'DiGraph' object has no attribute 'node'

**Comment by pmneila** [comment]
Hi @rajkataria 

Thanks for letting me know. I will fix this.

**Comment by pmneila** [comment]
Took some time but this is fixed now. Thank you again for the notice :)

Best.
