### ISSUE TITLE
add to conda-forge

### ISSUE THREAD

**Issue by martibosch** [pmneila/PyMaxflow#53]
Hello,

I am trying to add the [detectree](https://github.com/martibosch/detectree) library (which uses PyMaxflow) to conda-forge, however that requires PyMaxflow to also be in conda-forge. It should be very easy to do so (e.g., using [grayskull](https://github.com/conda-incubator/grayskull) as in `grayskull pypi PyMaxflow`).

I am happy to help if that interests you - it is actually quite easy. Let me know what you think. Best,
Martí

**Comment by martibosch** [comment]
I have submitted [a PR](https://github.com/conda-forge/staged-recipes/pull/15079) with a conda recipe so that the package can be installed from conda-forge.

**Comment by pmneila** [comment]
Hi, @martibosch,

That's great, thank you for your work!

Just a minor comment: the core of PyMaxflow is licensed under the GPL 3, so I think PyMaxflow should also use GPL 3, not the GPL 1. Could you please update the license file accordingly?

**Comment by martibosch** [comment]
Hello @pmneila,

I have [amended the commit](https://github.com/conda-forge/staged-recipes/commit/7b6838a73821da9c7640c1047bde224c7ae58e89) by changing GPL 1 for GPL 3.

Let me know if any further amendments are required. Best,
Martí

**Comment by martibosch** [comment]
closing as the PR has been merged.
