### ISSUE TITLE
Inconsistent Documentation

### ISSUE THREAD

**Issue by lucidBrot** [pmneila/PyMaxflow#54]
I'm revisiting my notes from a lecture where we were using this library, and recall that some of us were confused by the documentation. I'm not entirely certain, but these are my observations:

* The text and example at [this docs page](http://pmneila.github.io/PyMaxflow/maxflow.html#module-maxflow) refer to `g.get_segments()`. A function which does not seem to exist, as confirmed by [a search in this repo](https://github.com/pmneila/PyMaxflow/search?q=get_segments)

* [This page](http://pmneila.github.io/PyMaxflow/tutorial.html) in the docs clearly states for the existing function `get_segment` without a trailing `s`:
  > The method get_segment returns 1 when the given node belongs to the partition of the source node (i.e., the minimum cut severs the terminal edge from the node to the sink), or 0 otherwise   

  But then shows an example where the segment of the node 0 is said to be `1` and it is depicted on the picture as belonging to the sink, not the source. This is inconsistent.

* The [underlying c code](https://github.com/pmneila/PyMaxflow/blob/d158445fe9b90d2bc880655681c1b61b16cbae76/maxflow/src/core/graph.h#L73) defines `SOURCE = 0, SINK = 1`. So I would assume that this is the correct way of assignment.
* There is a [test](https://github.com/pmneila/PyMaxflow/blob/d158445fe9b90d2bc880655681c1b61b16cbae76/test_maxflow.py#L21) using 0 as the source, underlining my belief.
* The documentation about the [get_segment function itself](http://pmneila.github.io/PyMaxflow/maxflow.html) does not state anything about this.

If you agree, it would make sense to clarify the documentation. :)

**Comment by pmneila** [comment]
Hi @lucidBrot,

Indeed, the documentation of the library is pretty outdated. I wrote it a long time ago and I haven't updated it very often as I think the library is rather simple to use and clear enough with the examples and docstrings.

However, regarding your comments:

- Indeed, there is no `get_segments` anymore. This function used to exist to retrieve the segments of all nodes, but was renamed to `get_all_segments` at some early stage of the code, and then removed and replaced by `get_grid_segments`.
- You are absolutely right with the other three comments. Numbers `0` and `1` are switched in the docs. I'm surprised nobody noticed that before.

I'll update the docs to fix the issues you found (and perhaps to fix some other minor issues). Thank you for letting me know.

**Comment by pmneila** [comment]
I just updated the docs. These issues should be solved now.

Thank you again for the suggestion!

**Comment by lucidBrot** [comment]
Thank you! That was a surprisingly fast response!
