### ISSUE TITLE
Remove nodes from graph

### ISSUE THREAD

**Issue by nsn88** [pmneila/PyMaxflow#57]
I need a grid-like graph and it would be a lot easier if I could build a grid graph first and then remove a couple of nodes, instead of building the graph node-by-node.

Is it possible to remove a node from an existing graph?

**Comment by pmneila** [comment]
Hi @nsn88,

No, unfortunately the core library of PyMaxflow does not support removing nodes and the associated edges. However, you can just avoid creating edges to those nodes. Given that PyMaxflow omits all the edges created to/from the node id -1, you can substitute the corresponding nodeids by -1. For example:
```python
import maxflow

g = maxflow.GraphFloat()
nodeids = g.add_grid_nodes((4, 5))
nodeids[1, 2] = -1
print(nodeids)
# [[ 0  1  2  3  4]
#  [ 5  6 -1  8  9]
#  [10 11 12 13 14]
#  [15 16 17 18 19]]
g.add_grid_edges(nodeids)
```

This code generates this graph:
![Figure_1](https://user-images.githubusercontent.com/1254337/136708734-c3ae9b8d-a05c-4002-bad6-652c1694391d.png)

Does that help with your problem?
