### ISSUE TITLE
Applicability to instance segmentation 

### ISSUE THREAD

**Issue by kevinjohncutler** [pmneila/PyMaxflow#64]
Hi @pmneila, I'm scoping out options for segmenting images based on affinity graphs (basically generated via DNNs, but much more convoluted than that), and I am wondering if maxflow can output labeled segments via `get_grid_segments`. From your reconstruction example, it looks like it just outputs a binary foreground/background designation for each node.

**Comment by pmneila** [comment]
Hi, @kevinjohncutler 

Indeed, the max-flow (and min-cut) algorithm is designed to divide a graph into two separate sets, and `get_grid_segments` returns the nodes belonging to each set. This means that the output of the algorithm will always be binary.

That said, there are several ways to use max-flow for multi-label image segmentation. PyMaxflow, for instance, implements the alpha expansion and alpha-beta swap methods, as described in [Boykov01](https://dl.acm.org/doi/10.1109/34.969114) (pdf [here](https://www.cs.cornell.edu/rdz/Papers/BVZ-iccv99.pdf)), in its `fastmin` module. Note that this implementation has limitations, allowing only 4-pixel connectivity with uniform pair-wise costs.

Another simple approach is described in [Ishikawa98](https://www.cnbc.cmu.edu/~tai/readings/v1model/geiger2.pdf), which involves assigning multiple graph nodes per pixel and transforming the binary output of max-flow into non-binary labels by determining which nodes of the pixel were assigned to the source or the sink sets.

However, in most cases, DNNs provide smooth segmentation labels and using max-flow to improve the results is unnecessary (though there are some exceptions where it may be helpful).

I hope this information helps. If you have any further questions, please let me know.

Best
