### ISSUE TITLE
Installation on Macbook M1 Sequoia 15.1.1

### ISSUE THREAD

**Issue by roaasoloh** [pmneila/PyMaxflow#66]
I appreciate helping in fixing the issue to install this powerful library.

Two years ago I had worked with it, but now I tried all the possible configuration and available solutions, whether here or google and didn't get any chance to have the code working.

I tried installing it using pip and it gives correct installation, I tried also to clone and make the full setup in another way, and the same error I got.

As well I tried making new environment with lower version for python, still nothing is working.

` pip install PyMaxflow
Collecting PyMaxflow
  Using cached PyMaxflow-1.3.0-cp311-cp311-macosx_10_9_universal2.whl
Requirement already satisfied: numpy in ./research/lib/python3.11/site-packages (from PyMaxflow) (2.1.3)
Installing collected packages: PyMaxflow
Successfully installed PyMaxflow-1.3.0
`

And here the error I'm getting:

```
Traceback (most recent call last):
  File "/Users/roaasoloh/Desktop/Roaa/research/Research/try.py", line 10, in <module>
    import maxflow  # PyMaxflow library for alpha-expansion
    ^^^^^^^^^^^^^^
  File "/Users/roaasoloh/Desktop/Roaa/research/Research/research/lib/python3.11/site-packages/maxflow/__init__.py", line 36, in <module>
    from . import _maxflow
  File "maxflow/src/_maxflow.pyx", line 2, in init maxflow._maxflow
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

Process finished with exit code 1
```

**Comment by martibosch** [comment]
This happens in linux too but it is almost certainly because you have numpy 2. Until a new release with numpy 2 compatible wheels comes, there are two possible workarounds:
- downgrade numpy to 1.26.4
- provided that you have all the requirements in your environment (numpy 2, cython...), you can installing manually following [the respective instructions in the README](https://github.com/pmneila/PyMaxflow?tab=readme-ov-file#manual-installation).

**Comment by roaasoloh** [comment]
Thank you. It worked with downgrading the numpy.

**Comment by pmneila** [comment]
I have just uploaded a new version of the library, compiled for the M1 and updated for NumPy 2.0, so it should work out of the box.

You can get the latest version with
```
python -m pip install --upgrade PyMaxflow
```

Best
